name: Play game

on:
  issue_comment:
    types: [created]

jobs:
  play-game:
    runs-on: ubuntu-latest

    steps:
      - name: Set browser
        env:
          BROWSER: firefox
      - name: Check for command
        if: contains(toJson(github.event.comment.body), '/game')
        run: |
          open game.html
