name: Play game

on:
  issue_comment:
    types: [created]

jobs:
  play-game:
    runs-on: ubuntu-latest

    steps:
      - name: Check for command
        if: contains(toJson(github.event.comment.body), '/game')
        run: |
          xdg-open game.html
