name: Dependency Graph

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install -g depgraph
      - run: |
          depgraph --file=Podfile --output=dependencies.png
      - uses: actions/upload-artifact@v2
        with:
          name: dependencies
          path: dependencies.png
